use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct KeyBinding {
    pub view: &'static str,
    pub key: &'static str,
    pub action: &'static str,
    pub description: &'static str,
}

pub fn all_keybindings() -> Vec<KeyBinding> {
    vec![
        // Global
        KeyBinding {
            view: "global",
            key: "?",
            action: "help",
            description: "Show help",
        },
        KeyBinding {
            view: "global",
            key: "c",
            action: "compose",
            description: "Compose new email",
        },
        // Mailbox List
        KeyBinding {
            view: "mailbox_list",
            key: "q",
            action: "quit",
            description: "Quit",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "n/j/Down",
            action: "next",
            description: "Next mailbox",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "p/k/Up",
            action: "prev",
            description: "Previous mailbox",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "Enter",
            action: "open",
            description: "Open mailbox",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "g",
            action: "refresh",
            description: "Refresh",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "+",
            action: "create_folder",
            description: "Create folder",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "d",
            action: "delete_folder",
            description: "Delete selected folder",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "u",
            action: "mark_all_read",
            description: "Mark all mail in selected folder read",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "x",
            action: "preview_retention",
            description: "Preview retention expiry list",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "X",
            action: "expire_retention",
            description: "Expire retained mail now",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "PgDn",
            action: "page_down",
            description: "Page down",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "PgUp",
            action: "page_up",
            description: "Page up",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "Home",
            action: "jump_top",
            description: "Jump to top",
        },
        KeyBinding {
            view: "mailbox_list",
            key: "End",
            action: "jump_bottom",
            description: "Jump to bottom",
        },
        // Email List
        KeyBinding {
            view: "email_list",
            key: "q",
            action: "back",
            description: "Back to mailbox list",
        },
        KeyBinding {
            view: "email_list",
            key: "n/j/Down",
            action: "next",
            description: "Next email",
        },
        KeyBinding {
            view: "email_list",
            key: "p/k/Up",
            action: "prev",
            description: "Previous email",
        },
        KeyBinding {
            view: "email_list",
            key: "Enter",
            action: "open",
            description: "Open email / thread reading view",
        },
        KeyBinding {
            view: "email_list",
            key: "t",
            action: "open_thread",
            description: "Open thread list view (same folder)",
        },
        KeyBinding {
            view: "email_list",
            key: "T",
            action: "open_thread_cross_folder",
            description: "Open thread list view (all folders)",
        },
        KeyBinding {
            view: "email_list",
            key: "g",
            action: "refresh",
            description: "Refresh",
        },
        KeyBinding {
            view: "email_list",
            key: "r",
            action: "reply",
            description: "Reply to selected email",
        },
        KeyBinding {
            view: "email_list",
            key: "R",
            action: "reply_all",
            description: "Reply all to selected email",
        },
        KeyBinding {
            view: "email_list",
            key: "e",
            action: "dry_run_rules",
            description: "Dry-run rules on loaded messages",
        },
        KeyBinding {
            view: "email_list",
            key: "E",
            action: "run_rules",
            description: "Run rules on loaded messages",
        },
        KeyBinding {
            view: "email_list",
            key: "a",
            action: "archive",
            description: "Archive selected email/thread",
        },
        KeyBinding {
            view: "email_list",
            key: "d",
            action: "delete",
            description: "Move selected email/thread to deleted folder",
        },
        KeyBinding {
            view: "email_list",
            key: "D",
            action: "destroy",
            description: "Expire selected email/thread now (deleted folder only)",
        },
        KeyBinding {
            view: "email_list",
            key: "f",
            action: "toggle_flagged",
            description: "Toggle flagged",
        },
        KeyBinding {
            view: "email_list",
            key: "u",
            action: "toggle_read",
            description: "Toggle read/unread",
        },
        KeyBinding {
            view: "email_list",
            key: "m",
            action: "move",
            description: "Move to folder",
        },
        KeyBinding {
            view: "email_list",
            key: "s",
            action: "search",
            description: "Search in mailbox",
        },
        KeyBinding {
            view: "email_list",
            key: "l",
            action: "load_more",
            description: "Load more messages",
        },
        KeyBinding {
            view: "email_list",
            key: "Escape",
            action: "clear_search",
            description: "Clear search",
        },
        KeyBinding {
            view: "email_list",
            key: "PgDn",
            action: "page_down",
            description: "Page down",
        },
        KeyBinding {
            view: "email_list",
            key: "PgUp",
            action: "page_up",
            description: "Page up",
        },
        KeyBinding {
            view: "email_list",
            key: "Home",
            action: "jump_top",
            description: "Jump to top",
        },
        KeyBinding {
            view: "email_list",
            key: "End",
            action: "jump_bottom",
            description: "Jump to bottom",
        },
        // Thread View
        KeyBinding {
            view: "thread_view",
            key: "q",
            action: "back",
            description: "Back to email list",
        },
        KeyBinding {
            view: "thread_view",
            key: "n/j/Down",
            action: "next",
            description: "Next email",
        },
        KeyBinding {
            view: "thread_view",
            key: "p/k/Up",
            action: "prev",
            description: "Previous email",
        },
        KeyBinding {
            view: "thread_view",
            key: "Enter",
            action: "open",
            description: "Open email",
        },
        KeyBinding {
            view: "thread_view",
            key: "g",
            action: "refresh",
            description: "Refresh",
        },
        KeyBinding {
            view: "thread_view",
            key: "a",
            action: "archive",
            description: "Archive selected email",
        },
        KeyBinding {
            view: "thread_view",
            key: "d",
            action: "delete",
            description: "Move selected email to deleted folder",
        },
        KeyBinding {
            view: "thread_view",
            key: "D",
            action: "destroy",
            description: "Expire selected email now (deleted folder only)",
        },
        KeyBinding {
            view: "thread_view",
            key: "f",
            action: "toggle_flagged",
            description: "Toggle flagged",
        },
        KeyBinding {
            view: "thread_view",
            key: "u",
            action: "toggle_read",
            description: "Toggle read/unread",
        },
        KeyBinding {
            view: "thread_view",
            key: "PgDn",
            action: "page_down",
            description: "Page down",
        },
        KeyBinding {
            view: "thread_view",
            key: "PgUp",
            action: "page_up",
            description: "Page up",
        },
        KeyBinding {
            view: "thread_view",
            key: "Home",
            action: "jump_top",
            description: "Jump to top",
        },
        KeyBinding {
            view: "thread_view",
            key: "End",
            action: "jump_bottom",
            description: "Jump to bottom",
        },
        // Email View
        KeyBinding {
            view: "email_view",
            key: "q",
            action: "back",
            description: "Back to email list",
        },
        KeyBinding {
            view: "email_view",
            key: "n/j/Down",
            action: "scroll_down",
            description: "Scroll down",
        },
        KeyBinding {
            view: "email_view",
            key: "p/k/Up",
            action: "scroll_up",
            description: "Scroll up",
        },
        KeyBinding {
            view: "email_view",
            key: "Space/PgDn",
            action: "page_down",
            description: "Page down",
        },
        KeyBinding {
            view: "email_view",
            key: "PgUp",
            action: "page_up",
            description: "Page up",
        },
        KeyBinding {
            view: "email_view",
            key: "Home",
            action: "jump_top",
            description: "Jump to top",
        },
        KeyBinding {
            view: "email_view",
            key: "End",
            action: "jump_bottom",
            description: "Jump to bottom",
        },
        KeyBinding {
            view: "email_view",
            key: "r",
            action: "reply",
            description: "Reply",
        },
        KeyBinding {
            view: "email_view",
            key: "R",
            action: "reply_all",
            description: "Reply all",
        },
        KeyBinding {
            view: "email_view",
            key: "F",
            action: "forward",
            description: "Forward",
        },
        KeyBinding {
            view: "email_view",
            key: "A",
            action: "attachment",
            description: "Download/open attachment",
        },
        KeyBinding {
            view: "email_view",
            key: "h",
            action: "toggle_html",
            description: "Toggle HTML vs plain text body",
        },
        KeyBinding {
            view: "email_view",
            key: "v",
            action: "raw_headers",
            description: "Toggle raw headers (DKIM, Received, etc)",
        },
        KeyBinding {
            view: "email_view",
            key: "f",
            action: "toggle_flagged",
            description: "Toggle flagged",
        },
        KeyBinding {
            view: "email_view",
            key: "u",
            action: "toggle_read",
            description: "Toggle read/unread",
        },
        KeyBinding {
            view: "email_view",
            key: "D",
            action: "destroy",
            description: "Expire now (deleted folder only)",
        },
        KeyBinding {
            view: "email_view",
            key: "a",
            action: "archive",
            description: "Archive message",
        },
        KeyBinding {
            view: "email_view",
            key: "d",
            action: "delete",
            description: "Delete message (move to trash)",
        },
        KeyBinding {
            view: "email_view",
            key: "m",
            action: "move",
            description: "Move to mailbox (interactive picker)",
        },
        KeyBinding {
            view: "email_view",
            key: "b",
            action: "browse_urls",
            description: "Browse URLs found in message body",
        },
        KeyBinding {
            view: "email_view",
            key: "1-9",
            action: "open_url",
            description: "Open URL by number in configured browser",
        },
    ]
}
